# Generated by Django 4.2.1 on 2023-06-06 05:51

from django.db import migrations, models
import django.utils.timezone
import sqlalchemy.sql._elements_constructors


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='address',
            field=models.CharField(default=sqlalchemy.sql._elements_constructors.null, max_length=1000),
        ),
        migrations.AddField(
            model_name='salesman',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesman',
            name='phone_no',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesman',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
